### ISSUE TITLE
Installing with pnpm shows issues with package.json

### ISSUE THREAD

**Issue by snowe2010** [foxythemes/jira-cli#34]
```
###
### The "request" library is not installed automatically anymore.
### But is a dependency of "request-promise".
### Please install it with:
### npm install request --save
###

/Users/tyler.thrailkill/.node/pnpm-global/2/node_modules/.registry.npmjs.org/request-promise/4.2.4/node_modules/request-promise/lib/rp.js:23
    throw err;
    ^

Error: Cannot find module 'request'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at /Users/tyler.thrailkill/.node/pnpm-global/2/node_modules/.registry.npmjs.org/request-promise/4.2.4/node_modules/request-promise/lib/rp.js:11:16
    at module.exports (/Users/tyler.thrailkill/.node/pnpm-global/2/node_modules/.registry.npmjs.org/stealthy-require/1.1.1/node_modules/stealthy-require/lib/index.js:62:23)
    at Object.<anonymous> (/Users/tyler.thrailkill/.node/pnpm-global/2/node_modules/.registry.npmjs.org/request-promise/4.2.4/node_modules/request-promise/lib/rp.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/tyler.thrailkill/.node/pnpm-global/2/node_modules/.registry.npmjs.org/jira-cl/1.2.1/node_modules/jira-cl/lib/jira.js:43:23)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:657:17)
    at require (internal/modules/cjs/helpers.js:20:18)

```

It appears that the request library needs to be added to package.json.

**Comment by miguelmich** [comment]
I already included the `request` module in package and pushed a new version, can you please try installing again and tell me if it works for you? thanks!

**Comment by snowe2010** [comment]
@miguelmich 	hmm. I still get the same error. I might be misunderstanding why this is happening then... Maybe pnpm requires something else?

**Comment by miguelmich** [comment]
Yeah, can you please tell me what node and pnpm version do you have? I'll try to replicate your env with Docker

**Comment by snowe2010** [comment]
```
➜ node -v
v11.7.0

/ 
➜ pnpm -v
3.4.1
```

These are both brand new installs. I did all of this today.

**Comment by snowe2010** [comment]
@miguelmich 	I completely uninstalled all traces of node, npm, yarn, and pnpm and reinstalled just yarn and pnpm and jira-cli works 100% correctly now! Sorry for leading you astray. I am having other issues, but the tool isn't throwing those errors anymore.

**Comment by miguelmich** [comment]
I'm glad to hear that! :)
